#pragma once

#include <cstddef>
#include <memory>
#include <string>
#include <unordered_map>

namespace sabre::log
{
    /**
     * @brief Enumeration for logging levels.
     *
     * This enumeration defines the different levels of logging that can be used
     * to categorize log messages. Each level corresponds to a specific severity
     * of the log message.
     */
    enum class LoggingLevel : int
    {
        NOTSET = -1,
        EMERGENCY,
        ALERT,
        CRITICAL,
        ERROR,
        WARNING,
        NOTICE,
        INFO,
        DEBUG,
    };

    constexpr const char *LoggingLevelNames[] = {
        "EMERGENCY", "ALERT",  "CRITICAL", "ERROR",
        "WARNING",   "NOTICE", "INFO",     "DEBUG"};

    inline std::string LoggingLevelToString(LoggingLevel level)
    {
        int idx = static_cast<int>(level);
        if (idx < 0 || idx >= 8)
            return "UNKNOWN";
        return LoggingLevelNames[idx];
    }

    class LogManager;

    /**
     * @brief Class for logging messages for specific components.
     *
     * This class provides methods to log messages at various levels of
     * severity. It allows for structured logging with different logging levels,
     * such as DEBUG, INFO, WARNING, ERROR, etc. Each method corresponds to a
     * specific logging level, allowing for easy categorization and filtering of
     * log messages.
     *
     * This can be initiated for a specific component or module within the
     * Sabre framework, allowing for targeted logging. The logger can be used to
     * log messages that are relevant to the component it represents, making it
     * easier to track down issues or understand the flow of execution within
     * that component.
     */
    class Logger
    {
    public:
        using Ptr = Logger *;
        using SharedPtr = std::shared_ptr<Logger>;
        using UniquePtr = std::unique_ptr<Logger>;

    private:
        LogManager &_manager;
        std::string _name;

    public:
        /**
         * @brief Default constructor for Logger.
         *
         * This constructor initializes the Logger object with a specific name.
         */
        Logger(LogManager &manager, const std::string &name);

        /**
         * @brief Logs a message at the specified logging level.
         *
         * This method is the primary interface for logging messages. It allows
         * the user to specify the logging level and the message to be logged.
         *
         * @param level The logging level for the message.
         * @param message The message to be logged.
         */
        void log(const LoggingLevel level, const std::string &message);
    };

    /**
     * @brief Abstract base class for log handlers.
     *
     * This class defines the interface for log handlers, which are responsible
     * for processing log messages generated by the Logger class.
     */
    class LogHandler
    {
    public:
        using Ptr = LogHandler *;
        using SharedPtr = std::shared_ptr<LogHandler>;
        using UniquePtr = std::unique_ptr<LogHandler>;

        /**
         * @brief Virtual destructor.
         */
        virtual ~LogHandler() = default;

        /**
         * @brief Abstract method to handle log messages.
         *
         * @param level The logging level of the message.
         * @param loggerName The name of the logger that generated the message.
         * @param message The log message to be handled.
         */
        virtual void handleLog(const LoggingLevel level,
                               const std::string &loggerName,
                               const std::string &message) = 0;
    };

    /**
     * @brief Class for managing logging across the application.
     *
     * This class provides a centralized logging mechanism that allows for
     * setting the logging level, adding and removing log handlers, and logging
     * messages at various levels. It is designed to be used throughout the
     * Sabre framework to ensure consistent logging behavior.
     *
     * This class only has `static` members and cannot be initiated.
     */
    class LogManager
    {
    private:
        LoggingLevel _level = LoggingLevel::INFO;
        std::unordered_map<std::string, std::unique_ptr<LogHandler>> _handlers;

    public:
        LogManager() = default;
        LogManager(const LogManager &) = delete;
        LogManager(LogManager &&) = delete;
        LogManager &operator=(const LogManager &) = delete;

        /**
         * @brief Set the logging level for the application.
         *
         * This method allows the user to set the global logging level, which
         * determines the minimum severity of messages that will be logged.
         *
         * @param level The desired logging level.
         */
        void setLevel(LoggingLevel level);

        /**
         * @brief Get the current logging level.
         *
         * This method retrieves the current global logging level, which is used
         * to filter log messages based on their severity.
         *
         * @return The current logging level.
         */
        LoggingLevel getLevel();

        /**
         * @brief Log a message at the specified logging level.
         *
         * This method is used to log messages at various levels of severity.
         * It will only log messages that meet or exceed the current logging
         * level set for the application.
         *
         * @param level The logging level for the message.
         * @param loggerName The name of the logger that generated the message.
         * @param message The message to be logged.
         */
        void log(const LoggingLevel level, const std::string &loggerName,
                 const std::string &message);

        void log(const LoggingLevel level, const std::string &message);

        /**
         * @brief Add a log handler to the logging system.
         *
         * This method allows the user to register a log handler that will
         * receive log messages.
         */
        void addHandler(const std::string &identifier,
                        LogHandler::UniquePtr handler);

        void removeHandler(const std::string &identifier);
        LogHandler::UniquePtr &getHandler(const std::string &identifier);

        size_t getHandlerCount() const;

        Logger getLogger(const std::string &name);
    };

    class LogHelper
    {
    private:
        Logger::UniquePtr _logger = nullptr;

    public:
        void createLogger(LogManager &logManager, const std::string &name);
        void log(LoggingLevel level, const std::string &message);
        void reset();
    };
}; // namespace sabre::log