---
on:
  push:

jobs:
  unit-testing:
    name: Unit Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Project
        uses: threeal/cmake-action@v2.1.0
      - name: Run tests
        run: >
          cd build
          ctest
