---
on:
  push:

jobs:
  unit-testing:
    name: Unit Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install cmake
        run: sudo apt install cmake
      - name: Build project
        run: |
          cmake -S . -B build/
          cmake --build build/
      - name: Run tests
        run: |
          cd build
          ctest
